### ISSUE TITLE
Info_digitaltwin Update 

### ISSUE THREAD

**Issue by AlexandreHannelas** [threefoldfoundation/info_digitalself#18]
Description: 

Update DigitalTwin wiki and put an order in user flow 

- [ ] Vision Content - (Merge current "Our Vision" and " Why do we exist?"
- [ ] Technology 
        - Introduction Overview: Summary of how technologies around makes DT unique 
        - ThreeFold Grid 
        - Zero-OS 
        - Smart Contract for IT 
        - Digital Twin Server 
        - Planetary Secure Network 
        - Twin Phonebook 
        - Blockchain Database and 0-DB 
        - Quantum Safe File System 
- [ ] Get your Digital Twin 
- [ ] Check UserFlow and rearrange

**Comment by Vilnite** [comment]
See on circles tool: https://circles.threefold.me/project/despiegk-product_web_threefold/issue/59
