### ISSUE TITLE
missing wiki pages/broken links

### ISSUE THREAD

**Issue by rkhamis** [threefoldfoundation/info_digitalself#20]
- [ ] https://info.mydigitaltwin.io/#/twin__getting_started
- [ ] https://info.mydigitaltwin.io/#/yottagrid__engineering
- [ ] https://info.mydigitaltwin.io/#/twin__dev_architecture

**Comment by despiegk** [comment]
is old check what is still relevant here

**Comment by despiegk** [comment]
for sure putting something on major and then leave it here for weeks is not ok
