### ISSUE TITLE
do a sanity check

### ISSUE THREAD

**Issue by despiegk** [threefoldfoundation/info_digitalself#24]
if I walk over wiki its super easy to find issues,
use gitpod !!!

just correct or remove what is not correct

e.g. working_experiences in sidebar??? points to something else, this has nothing to do with tech

if issues which need more time make an issue for later or next milestone

**Comment by Vilnite** [comment]
See on circles tool: https://circles.threefold.me/project/despiegk-product_web_threefold/issue/61
