### ISSUE TITLE
make sure everyone in freeflow team knows how to use this repo with gitpod

### ISSUE THREAD

**Issue by despiegk** [threefoldfoundation/info_digitalself#26]
- everything in here is technical implementation of the freeflow, it needs to correspond
- don't loose ourselves in high level, strategic, more spiritual directions in this wiki
- make sure we all have gitpod, know how to use it,and have access to this

**Comment by Vilnite** [comment]
See on circles tool: https://circles.threefold.me/project/despiegk-product_web_threefold/issue/63
